name: dslink
version: 1.0.2
description: "DSA IoT Platform - DSLink SDK for Dart"
homepage: "http://iot-dsa.org"
documentation: "https://iot-dsa.github.io/docs/sdks/dart/"
dependencies:
  args: "^0.13.4"
  pointycastle:
    git:
      url: https://github.com/kaendfinger/pointycastle.git
      ref: bignum-v8
  logging: "^0.11.3"
  crypto: ">=0.9.2 <3.0.0"
  path: "^1.3.7"
  msgpack:
    git: https://github.com/IOT-DSA/msgpack.dart.git
  json_diff: "^0.1.2"
authors:
  - Kenneth Endfinger <k.endfinger@dglogik.com>
  - Rick Zhou <z.zhou@dglogik.com>
  - Michael Bullington <m.bullington@dglogik.com>
  - Matthew Butler <matthew.butler@acuitybrands.com>
  - Joel Trottier-Hebert <joel.trottier-hebert@acuitybrands.com>
dev_dependencies:
  test: "0.12.15+8"
  dsbroker:
    git: "https://github.com/IOT-DSA/broker-dart.git"
  browser: "^0.10.0"
environment:
  sdk: ">=1.13.0 <2.0.0"
executables:
  dsbeacon: beacon
