name: dslink
version: 0.5.7+1
description: "DSA IoT Platform - DSLink SDK for Dart"
homepage: "http://iot-dsa.org"
dependencies:
  args: ">=0.12.0 <0.14.0"
  bignum: ">=0.0.5 <0.1.0"
  cipher: ">=0.7.1 <1.0.0"
  logging: ">=0.9.0 <0.13.0"
  crypto: "^0.9.0"
  msgpack: "^0.3.0"
  collection: "^1.4.0"
authors:
  - Kenneth Endfinger <k.endfinger@dglogik.com>
  - Rick Zhou <z.zhou@dglogik.com>
  - Michael Bullington <m.bullington@dglogik.com>
  - Matthew Butler <m.butler@dglogik.com>
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  dsbroker:
    git: "https://github.com/IOT-DSA/broker-dart.git"
  browser: any
environment:
  sdk: ">=1.11.0"
executables:
  dsbeacon: beacon
